# Generated by Django 3.1.1 on 2020-09-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('habit_name', models.CharField(max_length=100)),
                ('is_used', models.BooleanField(default=True)),
            ],
        ),
    ]
