# Generated by Django 3.1.1 on 2020-09-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habit_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('actor', models.EmailField(max_length=200)),
                ('habit_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habit_category.habitcategory')),
            ],
        ),
    ]
