# Generated by Django 3.1.1 on 2020-10-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='due_date',
        ),
    ]
