# Generated by Django 3.1.1 on 2020-11-14 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_remove_habit_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='habit',
            name='end_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
