# Generated by Django 3.1.1 on 2020-11-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_auto_20201114_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(max_length=50),
        ),
    ]
